export enum PokemonType {
  Normal = "Normal",
  Fire = "Fire",
  Water = "Water",
  Electric = "Electric",
  Grass = "Grass",
  Ice = "Ice",
  Fighting = "Fighting",
  Poison = "Poison",
  Ground = "Ground",
  Flying = "Flying",
  Psychic = "Psychic",
  Bug = "Bug",
  Rock = "Rock",
  Ghost = "Ghost",
  Dragon = "Dragon",
}

export const pokemons: { name: string; type: PokemonType }[] = [
  { name: "Bulbasaur", type: PokemonType.Grass },
  { name: "Ivysaur", type: PokemonType.Grass },
  { name: "Venusaur", type: PokemonType.Grass },
  { name: "Charmander", type: PokemonType.Fire },
  { name: "Charmeleon", type: PokemonType.Fire },
  { name: "Charizard", type: PokemonType.Fire },
  { name: "Squirtle", type: PokemonType.Water },
  { name: "Wartortle", type: PokemonType.Water },
  { name: "Blastoise", type: PokemonType.Water },
  { name: "Caterpie", type: PokemonType.Bug },
  { name: "Metapod", type: PokemonType.Bug },
  { name: "Butterfree", type: PokemonType.Bug },
  { name: "Weedle", type: PokemonType.Bug },
  { name: "Kakuna", type: PokemonType.Bug },
  { name: "Beedrill", type: PokemonType.Bug },
  { name: "Pidgey", type: PokemonType.Normal },
  { name: "Pidgeotto", type: PokemonType.Normal },
  { name: "Pidgeot", type: PokemonType.Normal },
  { name: "Rattata", type: PokemonType.Normal },
  { name: "Raticate", type: PokemonType.Normal },
  { name: "Spearow", type: PokemonType.Normal },
  { name: "Fearow", type: PokemonType.Normal },
  { name: "Ekans", type: PokemonType.Poison },
  { name: "Arbok", type: PokemonType.Poison },
  { name: "Pikachu", type: PokemonType.Electric },
  { name: "Raichu", type: PokemonType.Electric },
  { name: "Sandshrew", type: PokemonType.Ground },
  { name: "Sandslash", type: PokemonType.Ground },
  { name: "Nidoran♀", type: PokemonType.Poison },
  { name: "Nidorina", type: PokemonType.Poison },
  { name: "Nidoqueen", type: PokemonType.Poison },
  { name: "Nidoran♂", type: PokemonType.Poison },
  { name: "Nidorino", type: PokemonType.Poison },
  { name: "Nidoking", type: PokemonType.Poison },
  { name: "Clefairy", type: PokemonType.Normal },
  { name: "Clefable", type: PokemonType.Normal },
  { name: "Vulpix", type: PokemonType.Fire },
  { name: "Ninetales", type: PokemonType.Fire },
  { name: "Jigglypuff", type: PokemonType.Normal },
  { name: "Wigglytuff", type: PokemonType.Normal },
  { name: "Zubat", type: PokemonType.Poison },
  { name: "Golbat", type: PokemonType.Poison },
  { name: "Oddish", type: PokemonType.Grass },
  { name: "Gloom", type: PokemonType.Grass },
  { name: "Vileplume", type: PokemonType.Grass },
  { name: "Paras", type: PokemonType.Bug },
  { name: "Parasect", type: PokemonType.Bug },
  { name: "Venonat", type: PokemonType.Bug },
  { name: "Venomoth", type: PokemonType.Bug },
  { name: "Diglett", type: PokemonType.Ground },
  { name: "Dugtrio", type: PokemonType.Ground },
  { name: "Meowth", type: PokemonType.Normal },
  { name: "Persian", type: PokemonType.Normal },
  { name: "Psyduck", type: PokemonType.Water },
  { name: "Golduck", type: PokemonType.Water },
  { name: "Mankey", type: PokemonType.Fighting },
  { name: "Primeape", type: PokemonType.Fighting },
  { name: "Growlithe", type: PokemonType.Fire },
  { name: "Arcanine", type: PokemonType.Fire },
  { name: "Poliwag", type: PokemonType.Water },
  { name: "Poliwhirl", type: PokemonType.Water },
  { name: "Poliwrath", type: PokemonType.Water },
  { name: "Abra", type: PokemonType.Psychic },
  { name: "Kadabra", type: PokemonType.Psychic },
  { name: "Alakazam", type: PokemonType.Psychic },
  { name: "Machop", type: PokemonType.Fighting },
  { name: "Machoke", type: PokemonType.Fighting },
  { name: "Machamp", type: PokemonType.Fighting },
  { name: "Bellsprout", type: PokemonType.Grass },
  { name: "Weepinbell", type: PokemonType.Grass },
  { name: "Victreebel", type: PokemonType.Grass },
  { name: "Tentacool", type: PokemonType.Water },
  { name: "Tentacruel", type: PokemonType.Water },
  { name: "Geodude", type: PokemonType.Rock },
  { name: "Graveler", type: PokemonType.Rock },
  { name: "Golem", type: PokemonType.Rock },
  { name: "Ponyta", type: PokemonType.Fire },
  { name: "Rapidash", type: PokemonType.Fire },
  { name: "Slowpoke", type: PokemonType.Water },
  { name: "Slowbro", type: PokemonType.Water },
  { name: "Magnemite", type: PokemonType.Electric },
  { name: "Magneton", type: PokemonType.Electric },
  { name: "Farfetch'd", type: PokemonType.Normal },
  { name: "Doduo", type: PokemonType.Normal },
  { name: "Dodrio", type: PokemonType.Normal },
  { name: "Seel", type: PokemonType.Water },
  { name: "Dewgong", type: PokemonType.Water },
  { name: "Grimer", type: PokemonType.Poison },
  { name: "Muk", type: PokemonType.Poison },
  { name: "Shellder", type: PokemonType.Water },
  { name: "Cloyster", type: PokemonType.Water },
  { name: "Gastly", type: PokemonType.Ghost },
  { name: "Haunter", type: PokemonType.Ghost },
  { name: "Gengar", type: PokemonType.Ghost },
  { name: "Onix", type: PokemonType.Rock },
  { name: "Drowzee", type: PokemonType.Psychic },
  { name: "Hypno", type: PokemonType.Psychic },
  { name: "Krabby", type: PokemonType.Water },
  { name: "Kingler", type: PokemonType.Water },
  { name: "Voltorb", type: PokemonType.Electric },
  { name: "Electrode", type: PokemonType.Electric },
  { name: "Exeggcute", type: PokemonType.Grass },
  { name: "Exeggutor", type: PokemonType.Grass },
  { name: "Cubone", type: PokemonType.Ground },
  { name: "Marowak", type: PokemonType.Ground },
  { name: "Hitmonlee", type: PokemonType.Fighting },
  { name: "Hitmonchan", type: PokemonType.Fighting },
  { name: "Lickitung", type: PokemonType.Normal },
  { name: "Koffing", type: PokemonType.Poison },
  { name: "Weezing", type: PokemonType.Poison },
  { name: "Rhyhorn", type: PokemonType.Ground },
  { name: "Rhydon", type: PokemonType.Ground },
  { name: "Chansey", type: PokemonType.Normal },
  { name: "Tangela", type: PokemonType.Grass },
  { name: "Kangaskhan", type: PokemonType.Normal },
  { name: "Horsea", type: PokemonType.Water },
  { name: "Seadra", type: PokemonType.Water },
  { name: "Goldeen", type: PokemonType.Water },
  { name: "Seaking", type: PokemonType.Water },
  { name: "Staryu", type: PokemonType.Water },
  { name: "Starmie", type: PokemonType.Water },
  { name: "Mr. Mime", type: PokemonType.Psychic },
  { name: "Scyther", type: PokemonType.Bug },
  { name: "Jynx", type: PokemonType.Ice },
  { name: "Electabuzz", type: PokemonType.Electric },
  { name: "Magmar", type: PokemonType.Fire },
  { name: "Pinsir", type: PokemonType.Bug },
  { name: "Tauros", type: PokemonType.Normal },
  { name: "Magikarp", type: PokemonType.Water },
  { name: "Gyarados", type: PokemonType.Water },
  { name: "Lapras", type: PokemonType.Water },
  { name: "Ditto", type: PokemonType.Normal },
  { name: "Eevee", type: PokemonType.Normal },
  { name: "Vaporeon", type: PokemonType.Water },
  { name: "Jolteon", type: PokemonType.Electric },
  { name: "Flareon", type: PokemonType.Fire },
  { name: "Porygon", type: PokemonType.Normal },
  { name: "Omanyte", type: PokemonType.Rock },
  { name: "Omastar", type: PokemonType.Rock },
  { name: "Kabuto", type: PokemonType.Rock },
  { name: "Kabutops", type: PokemonType.Rock },
  { name: "Aerodactyl", type: PokemonType.Rock },
  { name: "Snorlax", type: PokemonType.Normal },
  { name: "Articuno", type: PokemonType.Ice },
  { name: "Zapdos", type: PokemonType.Electric },
  { name: "Moltres", type: PokemonType.Fire },
  { name: "Dratini", type: PokemonType.Dragon },
  { name: "Dragonair", type: PokemonType.Dragon },
  { name: "Dragonite", type: PokemonType.Dragon },
  { name: "Mewtwo", type: PokemonType.Psychic },
  { name: "Mew", type: PokemonType.Psychic },
];
